server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://172.29.10.225:5432/microservice
    username: myusername
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
